var lang = new Array();
lang["ajax_preview_title"] =               "Show preview";
lang["close"] =                            "close";
lang["no_text"] =                          "- No text -";
lang["reply_link"] =                       "Post reply";
lang["fold_threads"] =                     "Fold threads";
lang["fold_threads_linktitle"] =           "Hide replies";
lang["expand_threads"] =                   "Expand threads";
lang["expand_threads_linktitle"] =         "Show replies";
lang["expand_fold_thread_linktitle"] =     "Expand / fold thread";
lang["fold_posting_title"] =               "Fold/expand posting";
lang["fold_postings"] =                    "Fold/expand";
lang["fold_postings_title"] =              "Fold or expand all postings";
lang["quote_label"] =                      "quote message";
lang["quote_title"] =                      "Insert quoted text of the posting to be replied on";
lang["bbcode_link_text"] =                 "Link text (optional):";
lang["bbcode_link_url"] =                  "Link address (URL):";
lang["bbcode_image_url"] =                 "Image address (URL):";
lang["bbcode_tex_code"] =                  "TeX formula (e.g. \\sqrt{x}):";
lang["error_no_name"] =                    "No name has been entered";
lang["error_no_subject"] =                 "No subject has been entered";
lang["error_no_text"] =                    "No \"message\" tex\'t has been entered";
lang["terms_of_use_error_posting"] =       "You have to agree to the terms of use in order to submit this message";
lang["delete_posting_confirm"] =           "Do you really want to delete this posting?";

var settings = new Array();
settings["session_prefix"] =               "mlf2_";
settings["hide_sidebar_image"] =           "images/plain.png";
settings["show_sidebar_image"] =           "images/plain.png";
settings["expand_thread_image"] =          "images/plain.png";
settings["fold_thread_image"] =            "images/plain.png";
settings["expand_thread_inactive_image"] = "images/plain.png";
settings["ajaxPreviewStructure"] =         "<div id=\"ajax-preview-top\"></div><div id=\"ajax-preview-main\"> <div id=\"ajax-preview-body\">  <img id=\"ajax-preview-close\" src=\"themes/default/images/close.png\" alt=\"[x]\" title=\"close\" />  <div id=\"ajax-preview-content\"></div> </div></div>";
settings["ajax_preview_image"] =           "images/ajax_preview.png";
settings["ajax_preview_throbber_image"] =  "images/throbber.gif";
settings["avatar_popup_width"] =           400;
settings["avatar_popup_height"] =          300;

var preload = new Array();
preload[0] =                               "images/bg_sprite_2.png";
preload[1] =                               "images/close.png";
preload[2] =                               "images/throbber.gif";

